### ISSUE TITLE
老哥，现在TLS 加密的tcp过来，怎么解析

### ISSUE THREAD

**Issue by gaoyang1120** [BailinSong/tcp-proxy#1]
老哥，现在TLS 加密的tcp过来，怎么解析，可以加个是否需要 加解密的功能

**Comment by BailinSong** [comment]
这个代理只关心tcp端口并不关心内部数据,因此加密解密功能需要服务端和客户端自行实现,使用这个项目代理过https的项目是可用的.

**Comment by gaoyang1120** [comment]
我知道，我是想截取客户端数据，结果是tls加过密的，能解出来吗

**Comment by BailinSong** [comment]
这个可能不容易当然如果都是你的服务并且有证书的应该可以

发自我的 iPhone
